#ifndef SPI_DB28_H
#define SPI_DB28_H

#include <avr/io.h>

// z80ctrl NG using AVR DB Series
#define SPI_PORT PORTA
#define SPI_MOSI_PIN PIN4_bm
#define SPI_MISO_PIN PIN5_bm
#define SPI_SCK_PIN PIN6_bm

#define SPI_DIR_CFG \
    SPI_PORT.DIRCLR = SPI_MISO_PIN; \
    SPI_PORT.DIRSET = SPI_MOSI_PIN | SPI_SCK_PIN; \
    IOX_CS_PORT.DIRSET = IOX_CS_PIN; \
    SD_CS_PORT.DIRSET = SD_CS_PIN;

#define SPI_SLOW SPI0.CTRLA = (SPI0.CTRLA & ~SPI_PRESC_gm) | SPI_PRESC_DIV128_gc | SPI_CLK2X_bm
#define SPI_FAST SPI0.CTRLA = (SPI0.CTRLA & ~SPI_PRESC_gm) | SPI_PRESC_DIV4_gc | SPI_CLK2X_bm

#define SPI_PHASE0 SPI0.CTRLB = (SPI0.CTRLB & ~SPI_MODE_gm) | SPI_MODE_0_gc
#define SPI_PHASE1 SPI0.CTRLB = (SPI0.CTRLB & ~SPI_MODE_gm) | SPI_MODE_1_gc

#define SPI_ENABLE SPI0.CTRLA |= SPI_ENABLE_bm
#define SPI_DISABLE SPI0.CTRLA &= ~SPI_ENABLE_bm

#define SPI_MASTER SPI0.CTRLA = SPI_MASTER_bm

#define SPI_DATA SPI0_DATA
#define SPI_READY (SPI0_INTFLAGS & SPI_RXCIF_bm)

#define MISO_LO SPI_PORT.OUTCLR = SPI_MISO_PIN
#define MISO_HI SPI_PORT.OUTSET = SPI_MISO_PIN
#define GET_MISO SPI_PORT.IN & SPI_MISO_PIN

#ifdef MISO_INPUT_PULLUP
#define MISO_INPUT           \
    SPI_MISO_PORT.DIRCLR = SPI_MISO_PIN; \
    MISO_HI;
#define MISO_OUTPUT         \
    SPI_MISO_PORT.DIRSET = SPI_MISO_PIN; \
    MISO_LO;
#else
#define MISO_INPUT SPI_MISO_PORT.DIRCLR = SPI_MISO_PIN
#define MISO_OUTPUT SPI_MISO_PORT.DIRSET = SPI_MISO_PIN
#endif

#define SCK_LO SPI_PORT.OUTCLR = SPI_SCK_PIN
#define SCK_HI SPI_PORT.OUTSET = SPI_SCK_PIN

#endif