inline void halt_input(void);
inline uint8_t get_halt(void);
inline void ioack_output(void);
inline uint8_t get_ioack(void);
inline void ioack_hi(void);
inline void ioack_lo(void);
inline void int_output(void);
inline uint8_t get_int(void);
inline void int_lo(void);
inline void int_hi(void);
inline void nmi_output(void);
inline uint8_t get_nmi(void);
inline void nmi_lo(void);
inline void nmi_hi(void);
inline void reset_output(void);
inline uint8_t get_reset();
inline void reset_lo(void);
inline void reset_hi(void);
inline void busrq_output(void);
inline uint8_t get_busrq(void);
inline void busrq_lo(void);
inline void busrq_hi(void);
inline void busack_input(void);
inline uint8_t get_busack(void);
inline void ctrl_input(void);
inline void ctrl_output(void);
inline void m1_input(void);
inline uint8_t get_m1(void);
inline uint8_t get_mreq(void);
inline void mreq_hi(void);
inline void mreq_lo(void);
inline uint8_t get_iorq(void);
inline void iorq_hi(void);
inline void iorq_lo(void);
inline uint8_t get_rd(void);
inline void rd_hi(void);
inline void rd_lo(void);
inline uint8_t get_wr(void);
inline void wr_hi(void);
inline void wr_lo(void);
inline void rfsh_input(void);
inline uint8_t get_rfsh(void);
inline void addr_input(void);
inline void addr_output(void);
inline uint8_t get_addrlo(void);
inline void set_addrlo(uint8_t addr);
inline uint8_t get_addrhi(void);
inline void set_addrhi(uint8_t addr);
inline uint16_t get_addr(void);
inline void set_addr(uint16_t addr);
inline void bank_output(void);
inline uint8_t get_bank(void);
inline void set_bank(uint8_t bank);
inline void data_input(void);
inline void data_output(void);
inline uint8_t get_data(void);
inline void set_data(uint8_t data);
inline void clk_output(void);
inline uint8_t get_clk(void);
inline void clk_hi(void);
inline void clk_lo(void);
inline void clk_tick(void);
inline void clk_run(void);
inline void clk_stop(void);
void bus_master(void);
void bus_slave(void);
void bus_init(void);
void bus_status(void);
void read_mem(uint16_t addr, uint8_t * buf, uint16_t len);
void write_mem(uint16_t addr, uint8_t * buf, uint16_t len);