#ifndef OPCODES_H
#define OPCODES_H

// Reference: http://www.z80.info/z80oplist.txt

// First byte encodes instruction type:
// 1 = single byte immediate operand
// 2 = two byte address operand
// + = one byte relative address operand
// * = two byte opcode
// other = single byte instruction (no operand)

char *opcodes[] = {
        "nop",
        "2ld bc,&%04x",
        "ld (bc),a",
        "inc bc",
        "inc b",
        "dec b",
        "1ld b,&%02x",
        "rlca",
        "ex af,af'",
        "add hl,bc",
        "ld a,(bc)",
        "dec bc",
        "inc c",
        "dec c",
        "1ld c,&%02x",
        "rrca",
        "+djnz &%04x",
        "2ld de,&%04x",
        "ld (de),a",
        "inc de",
        "inc d",
        "dec d",
        "1ld d,&%02x",
        "rla",
        "+jr &%04x",
        "add hl,de",
        "ld a,(de)",
        "dec de",
        "inc e",
        "dec e",
        "1ld e,&%02x",
        "rra",
        "+jr nz,&%04x",
        "2ld hl,&%04x",
        "2ld (&%04x),hl",
        "inc hl",
        "inc h",
        "dec h",
        "1ld h,&%02x",
        "daa",
        "+jr z,&%04x",
        "add hl,hl",
        "2ld hl,(&%04x)",
        "dec hl",
        "inc l",
        "dec l",
        "1ld l,&%02x",
        "cpl",
        "+jr nc,&%04x",
        "2ld sp,&%04x",
        "2ld (&%04x),a",
        "inc sp",
        "inc (hl)",
        "dec (hl)",
        "1ld (hl),&%02x",
        "scf",
        "+jr c,&%04x",
        "add hl,sp",
        "2ld a,(&%04x)",
        "dec sp",
        "inc a",
        "dec a",
        "1ld a,&%02x",
        "ccf",
        "ld b,b",
        "ld b,c",
        "ld b,d",
        "ld b,e",
        "ld b,h",
        "ld b,l",
        "ld b,(hl)",
        "ld b,a",
        "ld c,b",
        "ld c,c",
        "ld c,d",
        "ld c,e",
        "ld c,h",
        "ld c,l",
        "ld c,(hl)",
        "ld c,a",
        "ld d,b",
        "ld d,c",
        "ld d,d",
        "ld d,e",
        "ld d,h",
        "ld d,l",
        "ld d,(hl)",
        "ld d,a",
        "ld e,b",
        "ld e,c",
        "ld e,d",
        "ld e,e",
        "ld e,h",
        "ld e,l",
        "ld e,(hl)",
        "ld e,a",
        "ld h,b",
        "ld h,c",
        "ld h,d",
        "ld h,e",
        "ld h,h",
        "ld h,l",
        "ld h,(hl)",
        "ld h,a",
        "ld l,b",
        "ld l,c",
        "ld l,d",
        "ld l,e",
        "ld l,h",
        "ld l,l",
        "ld l,(hl)",
        "ld l,a",
        "ld (hl),b",
        "ld (hl),c",
        "ld (hl),d",
        "ld (hl),e",
        "ld (hl),h",
        "ld (hl),l",
        "halt",
        "ld (hl),a",
        "ld a,b",
        "ld a,c",
        "ld a,d",
        "ld a,e",
        "ld a,h",
        "ld a,l",
        "ld a,(hl)",
        "ld a,a",
        "add a,b",
        "add a,c",
        "add a,d",
        "add a,e",
        "add a,h",
        "add a,l",
        "add a,(hl)",
        "add a,a",
        "adc a,b",
        "adc a,c",
        "adc a,d",
        "adc a,e",
        "adc a,h",
        "adc a,l",
        "adc a,(hl)",
        "adc a,a",
        "sub a,b",
        "sub a,c",
        "sub a,d",
        "sub a,e",
        "sub a,h",
        "sub a,l",
        "sub a,(hl)",
        "sub a,a",
        "sbc a,b",
        "sbc a,c",
        "sbc a,d",
        "sbc a,e",
        "sbc a,h",
        "sbc a,l",
        "sbc a,(hl)",
        "sbc a,a",
        "and b",
        "and c",
        "and d",
        "and e",
        "and h",
        "and l",
        "and (hl)",
        "and a",
        "xor b",
        "xor c",
        "xor d",
        "xor e",
        "xor h",
        "xor l",
        "xor (hl)",
        "xor a",
        "or b",
        "or c",
        "or d",
        "or e",
        "or h",
        "or l",
        "or (hl)",
        "or a",
        "cp b",
        "cp c",
        "cp d",
        "cp e",
        "cp h",
        "cp l",
        "cp (hl)",
        "cp a",
        "ret nz",
        "pop bc",
        "2jp nz,&%04x",
        "2jp &%04x",
        "2call nz,&%04x",
        "push bc",
        "1add a,&%02x",
        "rst &00",
        "ret z",
        "ret",
        "2jp z,&%04x",
        "**** cb",
        "2call z,&%04x",
        "2call &%04x",
        "1adc a,&%02x",
        "rst &08",
        "ret nc",
        "pop de",
        "2jp nc,&%04x",
        "1out (&%02x),a",
        "2call nc,&%04x",
        "push de",
        "1sub a,&%02x",
        "rst &10",
        "ret c",
        "exx",
        "2jp c,&%04x",
        "1in a,(&%02x)",
        "2call c,&%04x",
        "**** dd",
        "1sbc a,&%02x",
        "rst &18",
        "ret po",
        "pop hl",
        "2jp po,&%04x",
        "ex (sp),hl",
        "2call po,&%04x",
        "push hl",
        "1and &%02x",
        "rst &20",
        "ret pe",
        "jp (hl)",
        "2jp pe,&%04x",
        "ex de,hl",
        "2call pe,&%04x",
        "**** ed",
        "1xor &%02x",
        "rst &28",
        "ret p",
        "pop af",
        "2jp p,&%04x",
        "di",
        "2call p,&%04x",
        "push af",
        "1or &%02x",
        "rst &30",
        "ret m",
        "ld sp,hl",
        "2jp m,&%04x",
        "ei",
        "2call m,&%04x",
        "**** fd",
        "1cp &%02x",
        "rst &38"
};
#endif